### ISSUE TITLE
[bug]: Getting an code: 'ECONNREFUSED' on port 80, when trying to send login/signup request.

### ISSUE THREAD

**Issue by absolutemadla8** [makeplane/plane#477] opened 2023-03-18 06:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
plane  | TypeError: fetch failed
plane  |     at Object.fetch (node:internal/deps/undici/undici:11413:11)
plane  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
plane  |     at async requiredAuth (/app/apps/app/.next/server/chunks/775.js:44:22)
plane  |     at async homePageRedirect (/app/apps/app/.next/server/chunks/775.js:101:18)
plane  |     at async Object.renderToHTML (/app/node_modules/next/dist/server/render.js:508:20)
plane  |     at async doRender (/app/node_modules/next/dist/server/base-server.js:669:38)
plane  |     at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/app/node_modules/next/dist/server/base-server.js:778:28)
plane  |     at async /app/node_modules/next/dist/server/response-cache/index.js:80:36 {
plane  |   cause: Error: connect ECONNREFUSED 127.0.0.1:80
plane  |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
plane  |     errno: -111,
plane  |     code: 'ECONNREFUSED',
plane  |     syscall: 'connect',
plane  |     address: '127.0.0.1',
plane  |     port: 80
plane. |   }
plane  | }
```
These are my nginx logs

```
172.20.0.1 - - [18/Mar/2023:06:01:25 +0000] "POST /api/magic-sign-in/ HTTP/1.1" 200 1868 "http://127.0.0.1:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
172.20.0.1 - - [18/Mar/2023:06:01:25 +0000] "GET /api/users/me/ HTTP/1.1" 200 1287 "http://127.0.0.1:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"

```

### Steps to reproduce

1. docker-compose up --build
2. send signup request

### Environment

Production

### Version

Self-hosted

**Comment by pablohashescobar** [comment] 2023-03-20 22:12
Hi @absolutemadla8 can you let me know which github branch are you using for building the containers.

**Comment by absolutemadla8** [comment] 2023-03-24 06:55
I have tried master, develop and stage-release. I happens to all of them

**Comment by pablohashescobar** [comment] 2023-03-24 07:19
Hey @absolutemadla8 did you run setup.sh <INSTANCE_IP> before building the containers

**Comment by livvk** [comment] 2023-04-05 16:49
Hi

I ran into this issue myself while trying to try out self-hosted Plane today. I followed the commands listed in the readme for running in docker (latest version from the develop branch, which at the time of writing is at commit 6b8b981e1d657893ddfd9e902129edc74581e28d):

```sh
git clone https://github.com/makeplane/plane
cd plane
./setup.sh localhost
docker-compose up
```

I then logged in with the default credentials in the readme `captain@plane.so` and `password123`. I can see in my browser's network request logs that it received an access token back, and this made it in to the cookies. It then hangs on "Signing in. Please wait..." as the above error appears in the server logs.

The first thing that appears to happen after logging in is redirecting to the home page, which gets rendered with SSR, and fetches the user data from the backend api (see: `requiredAuth` in `lib/auth.ts`, as in the stack trace) to determine where to send the user next.

The problem is that when doing running on localhost and doing SSR, any `fetch` to a url starting with `${baseUrl}/api` is ending up as `http://localhost/api`, which gets resolved to `http://127.0.0.1/api` which is the loopback address of the docker container running the frontend. The request never makes it to the backend, nor to the nginx container to be proxied. The frontend container has nothing listening on port 80 hence the connection refused message.

While it's not a solution, I've tested this theory by editing the line shown below, which does make logging in work and takes me to onboarding as expected.
![Test code with an updated URL for the backend API call, using planebackend:8000 instead of the base URL from the environment variable](https://user-images.githubusercontent.com/2052337/230146212-5d78fa6a-1bca-40a0-b7a6-d25c92a65afa.png)

I expect this isn't an issue that I'd ever run into in production, where all fetches would be made to a domain name - that would work from both browser and SSR.

**Comment by ngetchell** [comment] 2023-04-07 00:35
I get this as well when running setup as localhost, hostname, fqdn, and network IP. 

I delete the git repo, remove the containers, delete the docker volumes, and rebuild the app between each attempt.

**Comment by ngetchell** [comment] 2023-04-07 00:37
``` logs
nginx          | <ipaddress> - - [07/Apr/2023:00:33:18 +0000] "GET /_next/static/chunks/pages/index-31abfa5fd623125e.js HTTP/1.1" 200 375 "http://<ipaddress>/signin" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0"
planefrontend  | TypeError: fetch failed
planefrontend  |     at Object.fetch (node:internal/deps/undici/undici:11413:11)
planefrontend  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
planefrontend  |     at async requiredAuth (/app/apps/app/.next/server/chunks/7775.js:44:22)
planefrontend  |     at async homePageRedirect (/app/apps/app/.next/server/chunks/7775.js:101:18)
planefrontend  |     at async Object.renderToHTML (/app/node_modules/next/dist/server/render.js:508:20)
nginx          | <ipaddress> - - [07/Apr/2023:00:33:18 +0000] "GET /_next/data/eTYpVAm2zQccIa95KEwU8/index.json HTTP/1.1" 200 81 "http://<ipaddress>/signin" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0"
planefrontend  |     at async doRender (/app/node_modules/next/dist/server/base-server.js:669:38)
planefrontend  |     at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/app/node_modules/next/dist/server/base-server.js:778:28)
planefrontend  |     at async /app/node_modules/next/dist/server/response-cache/index.js:80:36 {
planefrontend  |   cause: Error: connect ECONNREFUSED 127.0.0.1:80
planefrontend  |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
planefrontend  |     errno: -111,
planefrontend  |     code: 'ECONNREFUSED',
planefrontend  |     syscall: 'connect',
planefrontend  |     address: '127.0.0.1',
planefrontend  |     port: 80
planefrontend  |   }
planefrontend  | }
```

**Comment by src52** [comment] 2023-04-07 18:49
Same issue here.

**Comment by pablohashescobar** [comment] 2023-04-09 08:11
Hey all, we have fixed this in our develop branch and it should be fairly stable we are still testing it and fixing it.

**Comment by vihar** [comment] 2023-04-10 18:07
Closing this issue, fixed on our `develop` branch, will be promoted to production.

**Closed by vihar** 2023-04-10 18:07 UTC
Labels: bug, Plane
