### ISSUE TITLE
[support]: Cannot send registration email for new member

### ISSUE THREAD

**Issue by arminus** [makeplane/plane#1131] opened 2023-05-24 12:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm trying to test this on a public domain, i.e. I need to create a new user so that I can delete the default user (for which I can't change the password as it seems) - but that mail never gets sent.

### Steps to reproduce

I'm setting 

EMAIL_HOST="server:port"
EMAIL_HOST_USER="user"
EMAIL_HOST_PASSWORD="password"

source the .env and restart the stack, then add a new member in the UI.

I do get a green toast message, but no mail is being sent and there is also no error or anything in the docker logs of planerqworker so I wonder if this is even implemented yet?

### Browser

Mozilla Firefox

### Version

Self-hosted

**Comment by pablohashescobar** [comment] 2023-05-24 17:20
Hello @arminus, looks like the error is in your `EMAIL_HOST` variable can you please provide `EMAIL_PORT` as separate variable, you can add the `EMAIL_PORT` as a separate variable in the environment file.

**Comment by techguruagi** [comment] 2023-06-05 08:54
Same issue here. I do get a green toast message, but no mail is being sent and there is also no error or anything in the docker logs of planerqworker or planebackend

planebackendlog - "GET /api/workspaces/workspace/invitations/ HTTP/1.1" 200

Using Amazon SES SMTP credentials. Is there any way we can debug the issue.

**Comment by pablohashescobar** [comment] 2023-06-05 08:58
Hi @techguruagi, it would be awesome if you could send logs of the bgworker container.

**Comment by techguruagi** [comment] 2023-06-05 09:10
@pablohashescobar 

[2023-06-04 21:51:56,802: INFO/MainProcess] Task plane.bgtasks.issue_activites_task.issue_activity[207d76bb-91b2-4c08-9d9e-4fb202579189] received
[2023-06-04 21:51:56,854: INFO/ForkPoolWorker-8] Task plane.bgtasks.issue_activites_task.issue_activity[207d76bb-91b2-4c08-9d9e-4fb202579189] succeeded in 0.04990960500435904s: None
[2023-06-04 21:52:21,815: INFO/MainProcess] Task plane.bgtasks.issue_activites_task.issue_activity[6a7232bb-9a91-428d-81b5-be3200654910] received
[2023-06-04 21:52:21,872: INFO/ForkPoolWorker-8] Task plane.bgtasks.issue_activites_task.issue_activity[6a7232bb-9a91-428d-81b5-be3200654910] succeeded in 0.054240596015006304s: None
[2023-06-05 13:09:47,501: INFO/MainProcess] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[cfdb5bef-f6fc-40c2-b719-92cdb403eaeb] received
[2023-06-05 13:09:47,593: INFO/ForkPoolWorker-8] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[cfdb5bef-f6fc-40c2-b719-92cdb403eaeb] succeeded in 0.0891377029765863s: None
[2023-06-05 13:20:07,303: INFO/MainProcess] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[ef115901-b976-4100-b926-ef6fbd3cdbc6] received
[2023-06-05 13:20:07,370: INFO/ForkPoolWorker-8] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[ef115901-b976-4100-b926-ef6fbd3cdbc6] succeeded in 0.06337625999003649s: None
[2023-06-05 14:16:23,964: INFO/MainProcess] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[01b75160-5923-4507-82cd-a90b6b60f50e] received
[2023-06-05 14:16:24,042: INFO/ForkPoolWorker-8] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[01b75160-5923-4507-82cd-a90b6b60f50e] succeeded in 0.07480859800125472s: None
[2023-06-05 14:22:57,779: INFO/MainProcess] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[89e4ab2f-cc89-461d-acf6-a2a0867c65f4] received
[2023-06-05 14:22:57,823: INFO/ForkPoolWorker-8] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[89e4ab2f-cc89-461d-acf6-a2a0867c65f4] succeeded in 0.04185305698774755s: None

**Comment by ErnieBernie10** [comment] 2023-06-05 11:47
Having the same problem. Could someone give some more information on what to put in the email host. Is it the SMTP server?

**Comment by pablohashescobar** [comment] 2023-06-05 12:03
Hi, could you please verify if TLS is currently enabled? As per the settings, it is enabled for all instances. Additionally, I have created a pull request (#1206) to ensure that this setting is properly passed through the environment.

**Comment by require-dev** [comment] 2023-06-05 21:55
Is the `EMAIL_FROM` field filled in? 

Otherwise you’ll be sending from the default sender, which most smtp servers won’t allow. 

Also, try make sure you have the last version of the docker-compose.yml file!

**Comment by techguruagi** [comment] 2023-06-06 01:05
@pablohashescobar 

Pulled the latest code and added TLS =1 in the env. Still the issue exists.

**Comment by techguruagi** [comment] 2023-06-06 01:06
> Is the `EMAIL_FROM` field filled in?
> 
> Otherwise you’ll be sending from the default sender, which most smtp servers won’t allow.
> 
> Also, try make sure you have the last version of the docker-compose.yml file!

Yes, Have EMAIL_FROM value properly set

**Comment by alphaxr6** [comment] 2023-06-07 07:29
Hey

I encountered the same issue here, with the ```EMAIL_HOST``` ```EMAIL_PORT``` ```EMAIL_USERNAME``` ```EMAIL_PASSWORD``` set in the worker docker compose..

If you need more logs than what it was provided, feel free to ask

**Comment by pablohashescobar** [comment] 2023-06-10 08:36
Hello! we have made updates to the Docker setup. We would greatly appreciate it if you could take some time to test the new setup and check if this issue was fixed as our team could not replicate this issue.

**Comment by techguruagi** [comment] 2023-06-12 07:25
@pablohashescobar 

The issue still exists. Emails are not delivered and infact there are no errors as well.

**Comment by pablohashescobar** [comment] 2023-06-12 07:33
Hi @techguruagi, we are unable to reproduce this at our end there is an additional setting `EMAIL_USE_SSL` that is false by default we will update the setup to use this value as well from environment.

**Comment by techguruagi** [comment] 2023-06-12 09:03
@pablohashescobar 

That is possible. Just tried setting up the email setup for another tool using the same credentials and faced "SSL routines:ssl3_get_record:wrong version number" error, when the USE_SSL is true. Email worked when i set it to false.  

However you are saying in the Plane, EMAIL_USE_SSL is by default false. Anyway let me wait for the changes to use this value from the env to test and confirm

**Comment by techguruagi** [comment] 2023-06-14 10:05
@pablohashescobar 

Pls share if there is any update on this.

**Comment by pablohashescobar** [comment] 2023-06-14 10:32
Hi @techguruagi, I'm unable to replicate the issue at the moment. However, it appears that there might be an SSL problem. To address this, we're planning to introduce an additional environment variable that can control the SSL settings for the backend container. Our team is actively working on implementing this solution, and we'll share the development build shortly. Thank you for your patience.

**Comment by Farhaduneci** [comment] 2023-06-21 07:27
Hello,
I appreciate for the great work you have done on this project.

I am currently using a self-hosting setup via Docker, and I am experiencing the same issue. I have conducted some checks to try and identify the problem. If there is any log or data that could assist in identifying the issue, please let me know and I will gladly provide it.

This issue is preventing my team from using the platform, and it would be great to have it resolved as soon as possible.

Upon checking the request flow for registration and forgot email, everything seems to be functioning correctly, as @pablohashescobar has mentioned. I have also checked the `docker-compose` log for the `plane-worker` and `plane-api` services, and there are no errors present.

The default Django email sending process and also the configurations are OK, I tested the flow via the `django-shell`. 

```py
from django.core.mail import send_mail

send_mail(
    "Subject here",
    "Here is the message.",
    "from@example.com",
    ["to@example.com"],
    fail_silently=False,
)
```

> I have copied the code from the official docs.
> https://docs.djangoproject.com/en/4.2/topics/email

However, when I tested the default Django email sending process and configurations via the `django-shell`, the code worked perfectly. The issue seems to be with the `forgot_password` function located in `apiserver/plane/bgtasks/forgot_password_task.py`. Here is the code: 

https://github.com/makeplane/plane/blob/cf8c902473cf3a5f1fdffd7d0a4a605072186a5d/apiserver/plane/bgtasks/forgot_password_task.py#L15-L41

I have also ensured that no exceptions are raised during the email sending process.

Thank you for your attention to this matter, and I hope we can work together to find a solution to this issue.

**Comment by Farhaduneci** [comment] 2023-06-21 09:49
Dear team,
I believe I've spotted the problem. **There is no bug in the system**!

After thorough investigation, I have realized that there is no actual bug in the system. However, I did identify a problem with the broad exception handler on line 39 of the `forgot_password_task.py` file.

https://github.com/makeplane/plane/blob/cf8c902473cf3a5f1fdffd7d0a4a605072186a5d/apiserver/plane/bgtasks/forgot_password_task.py#L35-L41

Upon further inspection, I discovered that the issue was caused by an incorrect `FROM_ADDRESS` in my `.env` file, which was not registered on the SMTP server. Unfortunately, there were no logs available to indicate this error, and it appears that the assumption was made that all users would rely on Sentry to view errors.

I believe it would be beneficial to refactor the code to include logging messages for exceptions, allowing users to debug their configurations without relying on Sentry.

This would be especially useful for cases like mine where Sentry is not present in the stack.

I hope @arminus's issue be fixed by reviewing the `.env` variables too. :v:
Thank you for your attention to this matter.

**Comment by pablohashescobar** [comment] 2023-06-21 13:30
Hi @Farhaduneci, thank you for the update and thanks for the suggestion we will work on enabling logging for the background workers.

**Comment by pablohashescobar** [comment] 2023-07-02 09:56
Hi, there is an additional env which can be used for configuring the SSL `EMAIL_USE_SSL` which can be used to enable/disable the SSL setting. We have also enabled logs for background jobs when the `DEBUG` value is set to `1`.

**Comment by nolexio** [comment] 2023-07-03 18:30
Any update on this one? I tried all possible combinations, including adding FROM_ADDRESS, setting different EMAIL_PORT and corresponding EMAIL_USE_TLS and EMAIL_USE_SSL settings, but still no success.

Here are my complete config settings, just to make sure we are talking about the same things.

`EMAIL_HOST=mail.server.com
EMAIL_HOST_USER=from@address.com
EMAIL_HOST_PASSWORD=password
EMAIL_PORT=587/465
EMAIL_FROM=no-reply@nobis.me
EMAIL_USE_TLS=1/0
EMAIL_USE_SSL=0/1`

additionarly i tried adding the following value:
`FROM_ADDRESS=from@address.com`

help very much appreciated.

**Comment by pablohashescobar** [comment] 2023-07-03 18:35
Hi @nolexio, can you check if the email has been verified in the smtp also you can enable logs if you switch to debug mode to print the errors to stdout.

**Comment by nolexio** [comment] 2023-07-03 18:40
> Hi @nolexio, can you check if the email has been verified in the smtp also you can enable logs if you switch to debug mode to print the errors to stdout.

I've set `DEBUG=1`. 

## Worker
```
[2023-07-03 23:52:14,552: INFO/MainProcess] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[afc91d0f-c8cd-4cb5-b25d-042c527f6218] received
[2023-07-03 23:52:44,596: INFO/MainProcess] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[f048f77d-8291-4a74-ac9b-88848a2cf70a] received
[2023-07-03 23:54:24,874: WARNING/ForkPoolWorker-4] [Errno 110] Operation timed out
[2023-07-03 23:54:24,876: INFO/ForkPoolWorker-4] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[afc91d0f-c8cd-4cb5-b25d-042c527f6218] succeeded in 130.32370973800425s: None
[2023-07-03 23:54:55,594: WARNING/ForkPoolWorker-2] [Errno 110] Operation timed out
[2023-07-03 23:54:55,596: INFO/ForkPoolWorker-2] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[f048f77d-8291-4a74-ac9b-88848a2cf70a] succeeded in 130.9996686000086s: None
[2023-07-04 00:05:20,628: INFO/MainProcess] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[2f12b770-7e4e-4252-bb1a-1f08a73d9ebb] received
[2023-07-04 00:07:31,306: WARNING/ForkPoolWorker-4] [Errno 110] Operation timed out
[2023-07-04 00:07:31,308: INFO/ForkPoolWorker-4] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[2f12b770-7e4e-4252-bb1a-1f08a73d9ebb] succeeded in 130.6779960290005s: None
```

## API
```
Waiting for database...
Database available!
Operations to perform:
  Apply all migrations: auth, authtoken, contenttypes, db, sessions, taggit, token_blacklist
Running migrations:
  No migrations to apply.
Success
[2023-07-03 18:38:41 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-07-03 18:38:41 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2023-07-03 18:38:41 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-07-03 18:38:41 +0000] [10] [INFO] Booting worker with pid: 10
[2023-07-03 18:38:41 +0000] [10] [INFO] Made Psycopg2 Green
[2023-07-03 18:38:41 +0000] [11] [INFO] Booting worker with pid: 11
[2023-07-03 18:38:41 +0000] [11] [INFO] Made Psycopg2 Green
[2023-07-03 18:38:41 +0000] [12] [INFO] Booting worker with pid: 12
[2023-07-03 18:38:41 +0000] [12] [INFO] Made Psycopg2 Green
[2023-07-03 18:38:41 +0000] [13] [INFO] Booting worker with pid: 13
[2023-07-03 18:38:41 +0000] [13] [INFO] Made Psycopg2 Green
[2023-07-03 18:38:41 +0000] [14] [INFO] Booting worker with pid: 14
[2023-07-03 18:38:41 +0000] [14] [INFO] Made Psycopg2 Green
[2023-07-03 18:38:41 +0000] [15] [INFO] Booting worker with pid: 15
[2023-07-03 18:38:41 +0000] [16] [INFO] Booting worker with pid: 16
[2023-07-03 18:38:41 +0000] [16] [INFO] Made Psycopg2 Green
[2023-07-03 18:38:41 +0000] [15] [INFO] Made Psycopg2 Green
[2023-07-03 18:38:41 +0000] [17] [INFO] Booting worker with pid: 17
[2023-07-03 18:38:41 +0000] [17] [INFO] Made Psycopg2 Green
[2023-07-04 00:08:42 +0530] [10] [INFO] Started server process [10]
[2023-07-04 00:08:42 +0530] [10] [INFO] Waiting for application startup.
[2023-07-04 00:08:42 +0530] [10] [INFO] ASGI 'lifespan' protocol appears unsupported.
[2023-07-04 00:08:42 +0530] [10] [INFO] Application startup complete.
[2023-07-04 00:08:42 +0530] [13] [INFO] Started server process [13]
[2023-07-04 00:08:42 +0530] [13] [INFO] Waiting for application startup.
[2023-07-04 00:08:42 +0530] [13] [INFO] ASGI 'lifespan' protocol appears unsupported.
[2023-07-04 00:08:42 +0530] [13] [INFO] Application startup complete.
[2023-07-04 00:08:42 +0530] [12] [INFO] Started server process [12]
[2023-07-04 00:08:42 +0530] [12] [INFO] Waiting for application startup.
[2023-07-04 00:08:42 +0530] [12] [INFO] ASGI 'lifespan' protocol appears unsupported.
[2023-07-04 00:08:42 +0530] [12] [INFO] Application startup complete.
[2023-07-04 00:08:42 +0530] [11] [INFO] Started server process [11]
[2023-07-04 00:08:42 +0530] [11] [INFO] Waiting for application startup.
[2023-07-04 00:08:42 +0530] [11] [INFO] ASGI 'lifespan' protocol appears unsupported.
[2023-07-04 00:08:42 +0530] [11] [INFO] Application startup complete.
[2023-07-04 00:08:42 +0530] [15] [INFO] Started server process [15]
[2023-07-04 00:08:42 +0530] [15] [INFO] Waiting for application startup.
[2023-07-04 00:08:42 +0530] [15] [INFO] ASGI 'lifespan' protocol appears unsupported.
[2023-07-04 00:08:42 +0530] [15] [INFO] Application startup complete.
[2023-07-04 00:08:42 +0530] [17] [INFO] Started server process [17]
[2023-07-04 00:08:42 +0530] [17] [INFO] Waiting for application startup.
[2023-07-04 00:08:42 +0530] [17] [INFO] ASGI 'lifespan' protocol appears unsupported.
[2023-07-04 00:08:42 +0530] [17] [INFO] Application startup complete.
[2023-07-04 00:08:42 +0530] [14] [INFO] Started server process [14]
[2023-07-04 00:08:42 +0530] [14] [INFO] Waiting for application startup.
[2023-07-04 00:08:42 +0530] [14] [INFO] ASGI 'lifespan' protocol appears unsupported.
[2023-07-04 00:08:42 +0530] [14] [INFO] Application startup complete.
[2023-07-04 00:08:42 +0530] [16] [INFO] Started server process [16]
[2023-07-04 00:08:42 +0530] [16] [INFO] Waiting for application startup.
[2023-07-04 00:08:42 +0530] [16] [INFO] ASGI 'lifespan' protocol appears unsupported.
[2023-07-04 00:08:42 +0530] [16] [INFO] Application startup complete.
```

**Comment by pablohashescobar** [comment] 2023-07-03 19:03
Hi @nolexio, the operations are getting timed out can you check if the smtp server is responding well?

**Comment by nolexio** [comment] 2023-07-03 19:32
I'm using the exact same settings on a different project, where everything is working just fine.

**Comment by pablohashescobar** [comment] 2023-07-04 04:48
Got it @nolexio, can you maybe check with another smtp server because looks like the server is not responding which is causing a operation timeout.

**Comment by hzwjs** [comment] 2023-08-23 04:54
> @pablohashescobar
> 
> [2023-06-04 21:51:56,802: INFO/MainProcess] Task plane.bgtasks.issue_activites_task.issue_activity[207d76bb-91b2-4c08-9d9e-4fb202579189] received [2023-06-04 21:51:56,854: INFO/ForkPoolWorker-8] Task plane.bgtasks.issue_activites_task.issue_activity[207d76bb-91b2-4c08-9d9e-4fb202579189] succeeded in 0.04990960500435904s: None [2023-06-04 21:52:21,815: INFO/MainProcess] Task plane.bgtasks.issue_activites_task.issue_activity[6a7232bb-9a91-428d-81b5-be3200654910] received [2023-06-04 21:52:21,872: INFO/ForkPoolWorker-8] Task plane.bgtasks.issue_activites_task.issue_activity[6a7232bb-9a91-428d-81b5-be3200654910] succeeded in 0.054240596015006304s: None [2023-06-05 13:09:47,501: INFO/MainProcess] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[cfdb5bef-f6fc-40c2-b719-92cdb403eaeb] received [2023-06-05 13:09:47,593: INFO/ForkPoolWorker-8] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[cfdb5bef-f6fc-40c2-b719-92cdb403eaeb] succeeded in 0.0891377029765863s: None [2023-06-05 13:20:07,303: INFO/MainProcess] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[ef115901-b976-4100-b926-ef6fbd3cdbc6] received [2023-06-05 13:20:07,370: INFO/ForkPoolWorker-8] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[ef115901-b976-4100-b926-ef6fbd3cdbc6] succeeded in 0.06337625999003649s: None [2023-06-05 14:16:23,964: INFO/MainProcess] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[01b75160-5923-4507-82cd-a90b6b60f50e] received [2023-06-05 14:16:24,042: INFO/ForkPoolWorker-8] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[01b75160-5923-4507-82cd-a90b6b60f50e] succeeded in 0.07480859800125472s: None [2023-06-05 14:22:57,779: INFO/MainProcess] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[89e4ab2f-cc89-461d-acf6-a2a0867c65f4] received [2023-06-05 14:22:57,823: INFO/ForkPoolWorker-8] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[89e4ab2f-cc89-461d-acf6-a2a0867c65f4] succeeded in 0.04185305698774755s: None

Where are the logs located?

**Comment by juldum54** [comment] 2023-09-27 21:00
Hi! I'm having the same issue: when I click on "**Send reset link**" on the "**Reset your password**" page, a green success message appears, indicating that the email was successfully sent, but I never receive them. I use the exact same SMPT settings in Nextcloud and emails are sent. In case you were wondering, because I use the Gmail SMTP service, the password is a Google app-password. Also, a red error message appears when I try to enter an email that does not belong to a registered user, so that's apparently not a bug while searching for the user account from its email.

_.env_
```
# Email Settings
EMAIL_HOST="smtp.gmail.com"
EMAIL_HOST_USER="<myemail>@gmail.com"
EMAIL_HOST_PASSWORD="<mypassword>"
EMAIL_PORT=465
EMAIL_FROM="Plane <<myemail>@gmail.com>>"
EMAIL_USE_TLS="1"
EMAIL_USE_SSL="1"
```

Logs indicate that the user is found and that the email is sent:

_bgworker logs_
```
2023/09/27 13:46:33,stderr,"[2023-09-27 20:46:33,360: INFO/ForkPoolWorker-4] Task plane.bgtasks.forgot_password_task.forgot_password[4bf389f1-beeb-47db-8052-2d17488f284c] succeeded in 0.06332088448107243s: None
"
2023/09/27 13:46:33,stderr,"[2023-09-27 20:46:33,295: INFO/MainProcess] Task plane.bgtasks.forgot_password_task.forgot_password[4bf389f1-beeb-47db-8052-2d17488f284c] received
```

Any idea of what could cause this?

**Comment by cuishuang** [comment] 2023-10-17 11:17
Same question +1

**Comment by cuishuang** [comment] 2023-10-18 07:35
After all the hard work, I solved this problem.

 That is: use gmail... (I use some service providers and have major or minor problems). Also pay attention to the settings of `EMAIL_USE_TLS="1"` and `EMAIL_USE_SSL="0"`.

 Friendly reminder: You may also encounter a pitfall. When sending an email to log in, be sure to change ENABLE_MAGIC_LINK_LOGIN="1"

**Comment by codenoid** [comment] 2023-10-24 02:54
still no working, I receive no email

smtp server and creds are correct (tested with other smtp client)

![image](https://github.com/makeplane/plane/assets/14269809/15033229-1071-4bf6-863e-36f093c4662e)

**Comment by TEA-AIR-E** [comment] 2023-11-12 09:38
I too was having this error, where I would see a green status notifcation within the app but never recieve an invite email.

After enabing debug mode and checking the docker logs I could see this error msg:

> WARNING/ForkPoolWorker-16] {'test@gmail.com': (550, b'Verification failed for <noreply@mydomain.com>\nThe mail server does not recognize noreply@mydomain.com as a valid sender.\nSender verify failed')}

I fixed this by setting the EMAIL_FROM field to blank ""

# Email Settings
EMAIL_HOST="mydomain.com"
EMAIL_HOST_USER="noreply@mydomain.com"
EMAIL_HOST_PASSWORD="secret-password-here"
EMAIL_PORT="465"
EMAIL_FROM=""
EMAIL_USE_TLS="0"
EMAIL_USE_SSL="1"

**Comment by codenoid** [comment] 2023-11-12 09:42
this was solved by running 

docker compose up -d -f docker-compose.yml

instead of docker-compose-hub.yml

**Comment by InPrime-Tech** [comment] 2023-12-12 10:24
Is there any update on this, facing the same issue

**Comment by pablohashescobar** [comment] 2023-12-13 08:30
Hey @InPrime-Tech this issue seems to be with the email host can you check the email host variable for your setup.

**Comment by InPrime-Tech** [comment] 2023-12-13 10:52
Hey @pablohashescobar i have cross checked my email host and seems to be working fine on other applications with the same credentials, its basically an AWS SES SMTP server endpoint. Also, on the server nsloopup and telnet are working fine with the same credentials and port

**Comment by pablohashescobar** [comment] 2023-12-13 19:28
But the plane server is unable to connect to that is what the error indicates can you check if it is configured right in the `.env`.

**Comment by pablohashescobar** [comment] 2023-12-13 19:28
But the plane server is unable to connect to that is what the error indicates can you check if it is configured right in the `.env`.

**Comment by pablohashescobar** [comment] 2023-12-19 17:44
Hi, @InPrime-Tech, can you check this in the updated [release](https://github.com/makeplane/plane/releases/tag/v0.14.1-dev).

**Closed** 2023-12-19 17:45 UTC
Labels: 📖docs, 🆘help wanted, 🛫plane, 🏠self-hosted
