### ISSUE TITLE
[bug]: 413 Request Entity Too Large

### ISSUE THREAD

**Issue by AlinaSelivanova** [makeplane/plane#2347] opened 2023-10-03 09:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I upload a file, for example mp3, whose size exceeds 2 mb, an error 413 Request Entity Too Large occurs

### Steps to reproduce

1. Open the bug card;
2. Upload an mp3 file that is more than 2 Mb, but less than 5 Mb
3. Wait for it to load

https://github.com/makeplane/plane/assets/83757237/ca4365ea-2c4c-4c87-b97b-d61fd3904b46

### Browser

Google Chrome

### Version

Self-hosted

**Comment by NarayanBavisetti** [comment] 2024-01-15 07:18
Hey @AlinaSelivanova , we tried replicating this, but this is working completely fine. Can you check your `FILE_SIZE_LIMIT`
value that you might have configured in you env.

**Comment by mguptahub** [comment] 2024-02-21 06:45
Closing this issues as there is no further activity.

**Closed by mguptahub** 2024-02-21 06:45 UTC
Labels: 🐛bug, 🛫plane, 🏠self-hosted

**Comment by rizkyarlin** [comment] 2024-11-07 11:26
I experienced the same issue. 

![image](https://github.com/user-attachments/assets/87f6e6e8-c149-4704-a088-c8711de30433)
![image](https://github.com/user-attachments/assets/5d2ae635-4973-49b5-b237-1c53c1f55574)
<img width="371" alt="image" src="https://github.com/user-attachments/assets/7b12671a-2eb4-4195-8520-1548fc87005e">
<img width="783" alt="image" src="https://github.com/user-attachments/assets/1792428d-1d16-4c11-8eba-e24b46ccd099">

In my case I don't even get the **max file size** shown on the pop up like OP's screen recording.

**Comment by rizkyarlin** [comment] 2024-11-07 11:44
I got it fixed, the problem is in my nginx configuration.

```
client_max_body_size 5M;
```
