### ISSUE TITLE
[bug]:  Potential abuse for when user-signup is disabled but magic-link is enabled, 

### ISSUE THREAD

**Issue by Nathan13888** [makeplane/plane#4739] opened 2024-06-09 06:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Similar to #1792 

Invalid users are sent email magic-codes on demand on the login page, despite signups are disabled.

**Expected Behaviour**: user is warned that signups are disabled, and no email is sent.

![image](https://github.com/makeplane/plane/assets/29968201/13fb03e9-e61c-41aa-a36d-2152eeeaec1f)

### Steps to reproduce

- On `latest` tag (deployed today) to k8s. 
- Set the following in Postgres:
![image](https://github.com/makeplane/plane/assets/29968201/d8d2556b-4e9b-49c7-a42f-2626588ba453)
- Visit login `/` and enter non-existent email. Magic code is sent to user.

### Environment

Production

### Browser

Mozilla Firefox

### Variant

Self-hosted

### Version

v0.21.0

**Comment by pablohashescobar** [comment] 2024-06-12 06:34
@Nathan13888, the magic code would be sent but the user won't be able to create account. We will add an additional validation so that even the magic code is not being sent.

**Comment by Nathan13888** [comment] 2024-06-12 18:02
Yup, you're correct, that's the behavior I've observed too.

**Comment by pushya22** [comment] 2024-07-09 13:05
Hi @Nathan13888  closing the issue since the feature is working as intended. Please re-open in case of any further queries.

**Closed by pushya22** 2024-07-09 13:05 UTC
Labels: 🐛bug
