### ISSUE TITLE
[bug]: while selecting an icon for new projects, the entire tab closes

### ISSUE THREAD

**Issue by KavitaR45** [makeplane/plane#5319] opened 2024-08-07 09:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When selecting an icon while adding a new project, the entire tab closes.

I have attached the screen recording for reference.

[plane-tab-close.webm](https://github.com/user-attachments/assets/54c84fa4-85cf-491c-930b-2b1c73c50d02)

### Steps to reproduce

1. Add New Project from the sidebar
2. Try to change the emoji icon
3. Tab closes

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

latest

**Comment by sbaamoha** [comment] 2024-08-07 10:38
@vihar 
i can handle that,
can u assign it to me ?

**Comment by pushya22** [comment] 2024-08-07 10:55
hi @KavitaR45 we tried to reproduce the exact same issue from our side but it was working fine for us (Refer to video below).  am I missing something?

Uploading Screen Recording 2024-08-07 at 4.17.41 PM.mov…

**Comment by pushya22** [comment] 2024-08-07 10:57
hi @KavitaR45 we tried to reproduce the exact same issue from our side but it was working fine for us (Refer to video below). am I missing something?


https://github.com/user-attachments/assets/e97093e4-79b8-469a-b699-36aab4ebeabe

**Comment by sbaamoha** [comment] 2024-08-07 11:02
@vihar 
actually i found the problem. 
the problem is not passing closeOnSelect to the CustomEmojiIconPicker component as shown bellow:
`<CustomEmojiIconPicker
                isOpen={isOpen}
                handleToggle={(val: boolean) => setIsOpen(val)}
                className="flex items-center justify-center"
                buttonClassName="flex items-center justify-center"
                label={
                  <span className="grid h-11 w-11 place-items-center rounded-md bg-custom-background-80">
                    <Logo logo={value} size={20} />
                  </span>
                }
                onChange={(val: any) => {
                  let logoValue = {};

                  if (val?.type === "emoji")
                    logoValue = {
                      value: convertHexEmojiToDecimal(val.value.unified),
                      url: val.value.imageUrl,
                    };
                  else if (val?.type === "icon") logoValue = val.value;

                  onChange({
                    in_use: val?.type,
                    [val?.type]: logoValue,
                  });
                  setIsOpen(false);
                }}
                defaultIconColor={value.in_use && value.in_use === "icon" ? value.icon?.color : undefined}
                defaultOpen={
                  value.in_use && value.in_use === "emoji" ? EmojiIconPickerTypes.EMOJI : EmojiIconPickerTypes.ICON
                }
              />`
              
              and the solution is add closeOnSelect={false}

**Comment by KavitaR45** [comment] 2024-08-07 11:04
hi @vihar , so I rechecked it again in icognito mode. There it is working as expected.

**Comment by sbaamoha** [comment] 2024-08-07 11:28
![Capture](https://github.com/user-attachments/assets/6b03fe41-f59c-49e2-b364-cffa41f5faa7)

the role of close() here is : Closes the window.
idk why we need this

**Comment by pushya22** [comment] 2024-08-08 11:47
HI @sbaamoha Thank you for the suggestion. The issue occurs intermittently and affects multiple areas. We are working on a comprehensive fix, which will be included in our next release.

**Closed** 2024-08-10 18:04 UTC
Labels: 🐛bug

**Comment by RajatMathew** [comment] 2024-08-24 20:23
I had the same problem and noticed something strange.
Tried both on Arc and Brave on Mac

<hr>

### The issue is present when
#### (1) I click on sign up button in the landing page then try to start a new project

https://github.com/user-attachments/assets/839371e5-0409-48ab-8643-5a09f9ed5a72


#### (2) I go the /workspace route directly

https://github.com/user-attachments/assets/6829c623-8de3-480f-83b9-345dff50938d


<hr>

### The issue is not present when
#### (1) I go the /sign-up route directly

https://github.com/user-attachments/assets/d466bd1e-11a5-48ec-97d7-db54c549e35c
