### ISSUE TITLE
[bug]: Cursor gets stuck when using up down arrow keys in editor

### ISSUE THREAD

**Issue by JWalshe86** [makeplane/plane#4606] opened 2024-05-27 12:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

While using the editor, when I try moving up or down with the up or down keyboard keys, the cursor gets stuck. The only way I can move up or down the editor then is by pressing the left or right arrows which is very slow or the 'pg up' or 'pg dn' keys which may move too far

![image](https://github.com/makeplane/plane/assets/139468339/dec93a98-ccfc-4de3-bcc5-8930a1554cf1)

I expect to be able to use the up or down keyboard keys to move up or down the editor page without it getting stuck.

### Steps to reproduce

1. Go to 'Pages'
2. Create a document that's longer than the current page view height.
3. Try scroll up or down 
4. Once you try scroll above the current viewport height of your laptop, the cursor gets stuck.

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

Free Plan

**Comment by srinivaspendem** [comment] 2024-05-28 09:39
Hi @JWalshe86,
We're unable to replicate the issue you're experiencing. If you're still encountering this problem, could you please provide us with a video demonstrating the issue? This will help our team understand and address it more effectively.

**Comment by JWalshe86** [comment] 2024-05-28 14:16
Hi @srinivaspendem,
Please find video attached. Make sure to turn on the sound. Hope this helps.
Kind regards,
Jlhn

https://github.com/makeplane/plane/assets/139468339/1efc6bad-5a3d-4d05-aaf5-2ed5890a8401

**Comment by pushya22** [comment] 2024-06-03 11:42
@JWalshe86 Thanks for sharing the screengrab, we are working on a fix and will be pushed in one our future releases

**Comment by Palanikannan1437** [comment] 2024-06-06 10:24
Hey @JWalshe86, could you please help me with a few things since I'm not able to reproduce this issue 😅

1. Your machine's Operating System.
2. A screenshot of the console logs (if any).
3. Does this happen on all pages for you or just this specific one.
4. Incase it happens with all pages for you, could you help me with the sample content of the page you're facing this issue with?

The above things would be really helpful to me to get started on a fix! Thanks

**Comment by JWalshe86** [comment] 2024-06-06 10:52
Hey @Palanikannan1437 . No problem.
1. It's Windows 10.
2. 
![Plane-cursor-stuck-error](https://github.com/makeplane/plane/assets/139468339/6fcb6db8-26dc-435f-bd21-9b3bbf9cdcb6)
3. I checked there & it appeared to only happen on one specific page.
4. Upon further inspection, it appears to only happen on a line that begins with '//'. If I remove // from the beginning of a line it doesn't get stuck, when I put '//' back to the beginning of a line it gets stuck on that line again.

**Comment by Palanikannan1437** [comment] 2024-06-06 15:18
Thanks for the detailed example, this is a possible fix for this.

https://github.com/makeplane/plane/pull/4725

**Closed** 2024-06-10 11:57 UTC
Labels: 🐛bug
