### ISSUE TITLE
[bug]: mouse middle-click insert 'random' text

### ISSUE THREAD

**Issue by asters-marnec** [makeplane/plane#5957] opened 2024-11-05 16:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I am in an issue description and I click the middle button of the mouse an apparently random string is inserted at cursor position. This is particularly annoying when clicking on external links, since I would expect the link to open in a new tab. I say apparently random because (at the moment of writing) the click consistently inserts the string `handles`,  which is not something that I have in my clipboard, a piece of selected text or anything that I recognize.

### Steps to reproduce

1. Go to an issue description
2. Click the middle mouse button

### Environment

Production

### Browser

Mozilla Firefox

### Variant

Self-hosted

### Version

v0.23.1

**Comment by pushya22** [comment] 2024-11-07 09:47
Hi @asters-marnec, we're unable to reproduce this issue on our end. Could you let us know if this was a one-time occurrence, or if you're able to reproduce it consistently? If so, could you please share a screen recording of the issue?

**Comment by asters-marnec** [comment] 2024-11-07 14:30
I can consistently reproduce it on my system but maybe this is something related to my particular setting:
I'm running arch with wayland and running on zen browser, which are 3 things that can independently capture mouse input. I'm having this issue only in plane at the moment but my mouse middle btn does have a mapping to paste-clipboard functionality. I'll investigate if this is something related to my system.

**Comment by pushya22** [comment] 2024-11-15 12:36
Hi, @asters-marnec, We’re closing this issue as it appears to be specific to your system. However, please don’t hesitate to reopen it if you believe otherwise or need further assistance.

**Closed by pushya22** 2024-11-15 12:36 UTC
Labels: 🐛bug
