### ISSUE TITLE
[feature]: Time track Functionality

### ISSUE THREAD

**Issue by leopathu** [makeplane/plane#3102] opened 2023-12-12 18:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be better to have time track functionalities in this

### Why should this be worked on?

We can't able to track the time for the tasks

**Comment by vihar** [comment] 2023-12-18 18:11
Duplicate of #1184. @leopathu we'll shortly update on this on the main thread. Thanks for the feature request.

**Closed by vihar** 2023-12-18 18:11 UTC
