### ISSUE TITLE
[bug]: error downloading/installing @tiptap-pro/extension-unique-id

### ISSUE THREAD

**Issue by ramonov** [makeplane/plane#1899] opened 2023-08-18 06:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

when running docker compose up i am getting following error :

```
Docker compose build
[+] Building 78.6s (43/96)                                                                                        
 => [plane-plane-worker internal] load build definition from Dockerfile.api                                  0.0s
 => => transferring dockerfile: 1.25kB                                                                       0.0s
 => [plane-plane-worker internal] load .dockerignore                                                         0.0s
 => => transferring context: 2B                                                                              0.0s
 => [plane-plane-api internal] load metadata for docker.io/library/python:3.11.1-alpine3.17                  1.2s
 => [plane-plane-beat-worker internal] load .dockerignore                                                    0.0s
 => => transferring context: 2B                                                                              0.0s
 => [plane-plane-beat-worker internal] load build definition from Dockerfile.api                             0.0s
 => => transferring dockerfile: 1.25kB                                                                       0.0s
 => [plane-plane-web internal] load .dockerignore                                                            0.0s
 => => transferring context: 87B                                                                             0.0s
 => [plane-plane-web internal] load build definition from Dockerfile.web                                     0.0s
 => => transferring dockerfile: 2.11kB                                                                       0.0s
 => [plane-plane-api internal] load build definition from Dockerfile.api                                     0.0s
 => => transferring dockerfile: 1.25kB                                                                       0.0s
 => [plane-plane-api internal] load .dockerignore                                                            0.0s
 => => transferring context: 2B                                                                              0.0s
 => [plane-plane-web internal] load metadata for docker.io/library/node:18-alpine                            1.1s
 => [plane-plane-proxy internal] load build definition from Dockerfile                                       0.0s
 => => transferring dockerfile: 297B                                                                         0.0s
 => [plane-plane-proxy internal] load .dockerignore                                                          0.0s
 => => transferring context: 2B                                                                              0.0s
 => [plane-plane-proxy internal] load metadata for docker.io/library/nginx:1.25.0-alpine                     1.1s
 => [plane-plane-beat-worker internal] load build context                                                    0.0s
 => => transferring context: 12.64kB                                                                         0.0s
 => [plane-plane-api  1/17] FROM docker.io/library/python:3.11.1-alpine3.17@sha256:d8b0703ce84fe5a52d485f2  77.4s
 => [plane-plane-worker internal] load build context                                                         0.0s
 => => transferring context: 12.64kB                                                                         0.0s
 => [plane-plane-api internal] load build context                                                            0.1s
 => => transferring context: 12.64kB                                                                         0.0s
 => [plane-plane-proxy 1/5] FROM docker.io/library/nginx:1.25.0-alpine@sha256:2e776a66a3556f001aba13431b26e  0.0s
 => [plane-plane-proxy internal] load build context                                                          0.0s
 => => transferring context: 66B                                                                             0.0s
 => [plane-plane-web internal] load build context                                                            0.2s
 => => transferring context: 84.95kB                                                                         0.1s
 => [plane-plane-web runner  1/12] FROM docker.io/library/node:18-alpine@sha256:3482a20c97e401b56ac50ba8920  0.0s
 => CACHED [plane-plane-web runner  2/12] WORKDIR /app                                                       0.0s
 => CACHED [plane-plane-web runner  3/12] RUN addgroup --system --gid 1001 plane                             0.0s
 => CACHED [plane-plane-web runner  4/12] RUN adduser --system --uid 1001 captain                            0.0s
 => CACHED [plane-plane-proxy 2/5] RUN rm /etc/nginx/conf.d/default.conf                                     0.0s
 => CACHED [plane-plane-proxy 3/5] COPY nginx.conf.template /etc/nginx/nginx.conf.template                   0.0s
 => CACHED [plane-plane-proxy 4/5] COPY ./env.sh /docker-entrypoint.sh                                       0.0s
 => CACHED [plane-plane-proxy 5/5] RUN chmod +x /docker-entrypoint.sh                                        0.0s
 => CACHED [plane-plane-worker  2/17] WORKDIR /code                                                          0.0s
 => CACHED [plane-plane-worker  3/17] RUN apk --no-cache add     "libpq~=15"     "libxslt~=1.1"     "nodejs  0.0s
 => CACHED [plane-plane-worker  4/17] COPY requirements.txt ./                                               0.0s
 => CACHED [plane-plane-worker  5/17] COPY requirements ./requirements                                       0.0s
 => CACHED [plane-plane-worker  6/17] RUN apk add --no-cache libffi-dev                                      0.0s
 => [plane-plane-proxy] exporting to image                                                                   0.0s
 => => exporting layers                                                                                      0.0s
 => => writing image sha256:b07684edc2da3264afec4ed633664a337f6ffa0056f6b768e3ea94e779c28369                 0.0s
 => => naming to docker.io/library/plane-plane-proxy                                                         0.0s
 => CANCELED [plane-plane-worker  7/17] RUN apk add --no-cache --virtual .build-deps     "bash~=5.2"     "  74.3s
 => CACHED [plane-plane-web builder 2/6] RUN apk add --no-cache libc6-compat                                 0.0s
 => CACHED [plane-plane-web builder 3/6] WORKDIR /app                                                        0.0s
 => CACHED [plane-plane-web builder 4/6] RUN yarn global add turbo                                           0.0s
 => CACHED [plane-plane-web builder 5/6] COPY . .                                                            0.0s
 => CACHED [plane-plane-web builder 6/6] RUN turbo prune --scope=app --docker                                0.0s
 => CACHED [plane-plane-web installer  4/13] COPY .gitignore .gitignore                                      0.0s
 => CACHED [plane-plane-web installer  5/13] COPY --from=builder /app/out/json/ .                            0.0s
 => CACHED [plane-plane-web installer  6/13] COPY --from=builder /app/out/yarn.lock ./yarn.lock              0.0s
 => ERROR [plane-plane-web installer  7/13] RUN yarn install --network-timeout 500000                       74.0s
------
 > [plane-plane-web installer  7/13] RUN yarn install --network-timeout 500000:
#0 0.548 yarn install v1.22.19
#0 0.675 [1/4] Resolving packages...
#0 1.154 [2/4] Fetching packages...
#0 17.04 error An unexpected error occurred: "https://registry.tiptap.dev/@tiptap-pro%2fextension-unique-id/-/extension-unique-id-2.1.0.tgz: Request failed \"500 Internal Server Error\"".
#0 17.04 info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
#0 17.04 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn install --network-timeout 500000" did not complete successfully: exit code: 1
```

### Steps to reproduce

1. git clone https://github.com/makeplane/plane
2. cd plane
3. ./setup.sh localhost
4. docker-compose up

### Browser

Google Chrome

### Version

Cloud

**Comment by vihar** [comment] 2023-08-18 06:25
Hey @ramonov, we are still working on fixing the issues on the `develop` branch. Please set-up Plane from the `master` branch.

**Comment by kripainc** [comment] 2023-08-21 21:51
Master branch (59bdf222f5c) also encounters the same error:

0.575 [2/4] Fetching packages...
5.773 error An unexpected error occurred: "https://registry.tiptap.dev/@tiptap-pro%2fextension-unique-id/-/extension-unique-id-2.1.0.tgz: Request failed \"500 Internal Server Error\"".
5.773 info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
5.773 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by mzch** [comment] 2023-08-23 16:22
This also happens in `tags/v0.11-dev`.

**Comment by pablohashescobar** [comment] 2023-08-23 16:45
Hi @mzch just to confirm are you using the prebuilt images or building the images in local ?

**Comment by mzch** [comment] 2023-08-23 16:48
I tried to build an image in local.

**Comment by pablohashescobar** [comment] 2023-08-23 17:18
Hi @mzch, can you try using the pre-built images using `docker-compose-hub.yml`

**Comment by mzch** [comment] 2023-08-23 22:31
It went well! Thanks.

.p.s
Creating an account on https://tiptap.dev/ and putting auth code in `.npmrc`, I could build an image in local successfully.

**Comment by anibal-aguila** [comment] 2023-08-28 16:20
hi @mzch shared here the place where find this information...

![image](https://github.com/makeplane/plane/assets/49025536/359018e9-381d-4039-8d61-f17b26340345)

seems to be the same issue https://github.com/makeplane/plane/issues/1869#issuecomment-1687127880 in that case, Is there an option to use plane without relying on a third-party @pablohashescobar ?

thanks

**Comment by vihar** [comment] 2023-12-14 19:13
This issue has been resolved in https://github.com/makeplane/plane/pull/2209. To ensure the issue is fully resolved, we recommend upgrading to the latest version as detailed in our documentation ([docs](https://docs.plane.so/self-hosting/docker-compose#upgrading-from-v0-13-2-to-v0-14-x)). If you encounter any further issues, please do not hesitate to inform us, and we will be ready to assist you.

**Closed** 2023-12-14 19:14 UTC
Labels: 🐛bug, 🛫plane, 🏠self-hosted
