### ISSUE TITLE
[feature]: Hability yo choose first day of week

### ISSUE THREAD

**Issue by emmgfx** [makeplane/plane#4600] opened 2024-05-27 07:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It's necessary that users could choose the first day of week. 

### Why should this be worked on?

For a person which his first day of week is Monday, having it on the second position turns the UI very confusing. Actually, I put wrong dates on some tasks because of this.

**Comment by srinivaspendem** [comment] 2024-05-27 07:57
Closing as duplicate of #4270

**Closed by srinivaspendem** 2024-05-27 07:57 UTC
Labels: ✨feature
