### ISSUE TITLE
[bug]: Rearrange Favorites does not seem to work

### ISSUE THREAD

**Issue by michaelfedell** [makeplane/plane#5995] opened 2024-11-13 16:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Items in the "Favorites" section of the sidebar have a draggable icon and a popover which says "Drag to rearrange". However, upon dragging, these items never snap into place or are actually rearrangeable. Other sections have the same draggable icon, and when dragged will pop up a horizontal blue bar, marking their new arrangement. This does not function correctly for the favorites section

### Steps to reproduce

1. Attempt to drag an item in "Favorites" to a new order
![Screenshot 2024-11-13 at 8 04 36 AM](https://github.com/user-attachments/assets/617a38ca-9487-4076-9f18-0332fbf88787)
![Screenshot 2024-11-13 at 8 05 18 AM](https://github.com/user-attachments/assets/5fb57cee-43bd-4fa9-8f53-b2f6df886975)

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v1.4.0

**Comment by sriramveeraghanta** [comment] 2024-11-18 09:01
Hey @michaelfedell  

Thank you for bringing this issue to our attention. We have identified the root cause and are currently working on a fix, which will be included in our upcoming update scheduled to roll out in next few days.

**Comment by leedsjb** [comment] 2024-11-22 04:35
Thanks @sriramveeraghanta !

**Comment by leedsjb** [comment] 2024-11-30 20:58
@sriramveeraghanta which version is this issue resolved in? It appears v1.5.0 does not resolve the issue.

**Comment by sriramveeraghanta** [comment] 2024-12-04 07:13
We have fixed this issue after rolling out the v1.5.0, So the fix will be shipped as a part of next release. We will keep you posted through release notes.

**Comment by pushya22** [comment] 2024-12-11 09:02
Hi @leedsjb, This issue has been resolved in our latest release. Please upgrade to 1.6.0. If the issue persists, feel free to re-open it.

**Closed by pushya22** 2024-12-11 09:02 UTC
Labels: 🐛bug
