### ISSUE TITLE
[bug]: self-hosted on Ubuntu 23.10: docker container keeps restarting

### ISSUE THREAD

**Issue by corbolais** [makeplane/plane#3125] opened 2023-12-13 22:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
28c8041e39ad   makeplane/plane-backend:latest    "./bin/worker"           About an hour ago   Restarting (1) 34 seconds ago                                           plane-app_worker_1
9107ef1fd7c1   makeplane/plane-backend:latest    "./bin/beat"             About an hour ago   Restarting (1) 34 seconds ago                                           plane-app_beat-worker_1
c72bc2362bc6   makeplane/plane-backend:latest    "./bin/takeoff"          About an hour ago   Restarting (1) 34 seconds ago                                           plane-app_api_1
```

### Steps to reproduce

Using Ubuntu 23.10, install self-hosted plane as given in https://docs.plane.so/self-hosting/docker-compose .

The three docker containers above keep restarting.

`docker logs --tail 50 --follow --timestamps c72bc2362bc6`
`   django.db.utils.OperationalError: connection failed: FATAL:  database "plane:plane@plane-db/plane}" does not exist`

`docker logs --tail 50 --follow --timestamps 9107ef1fd7c1`
`   2023-12-13T22:20:46.806327567Z [2023-12-13 22:20:46,806: WARNING/MainProcess] connection failed: FATAL:  database "plane:plane@plane-db/plane}" does not exist`

`docker logs --tail 50 --follow --timestamps 28c8041e39ad`
```
2023-12-13T22:21:49.583254512Z Waiting for database...
2023-12-13T22:21:49.583302904Z Database available!
2023-12-13T22:21:52.325984305Z [2023-12-13 22:21:52,324: CRITICAL/MainProcess] Unrecoverable error: ValueError("invalid literal for int() with base 10: ':6379/}'")
2023-12-13T22:21:52.326039289Z Traceback (most recent call last):
2023-12-13T22:21:52.326046543Z   File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 202, in start
2023-12-13T22:21:52.326053416Z     self.blueprint.start(self)
2023-12-13T22:21:52.326059648Z   File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 112, in start
2023-12-13T22:21:52.326087661Z     self.on_start()
2023-12-13T22:21:52.326093983Z   File "/usr/local/lib/python3.11/site-packages/celery/apps/worker.py", line 135, in on_start
2023-12-13T22:21:52.326100425Z     self.emit_banner()
2023-12-13T22:21:52.326106457Z   File "/usr/local/lib/python3.11/site-packages/celery/apps/worker.py", line 169, in emit_banner
2023-12-13T22:21:52.326112769Z     ' \n', self.startup_info(artlines=not use_image))),
2023-12-13T22:21:52.326119030Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-13T22:21:52.326125302Z   File "/usr/local/lib/python3.11/site-packages/celery/apps/worker.py", line 231, in startup_info
2023-12-13T22:21:52.326131664Z     results=self.app.backend.as_uri(),
2023-12-13T22:21:52.326137696Z             ^^^^^^^^^^^^^^^^
2023-12-13T22:21:52.326143687Z   File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 1293, in backend
2023-12-13T22:21:52.326149999Z     self._backend = self._get_backend()
2023-12-13T22:21:52.326156031Z                     ^^^^^^^^^^^^^^^^^^^
2023-12-13T22:21:52.326162052Z   File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 968, in _get_backend
2023-12-13T22:21:52.326168424Z     return backend(app=self, url=url)
2023-12-13T22:21:52.326174476Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-13T22:21:52.326180477Z   File "/usr/local/lib/python3.11/site-packages/celery/backends/redis.py", line 272, in __init__
2023-12-13T22:21:52.326186789Z     self.connparams = self._params_from_url(url, self.connparams)
2023-12-13T22:21:52.326192931Z                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-13T22:21:52.326199032Z   File "/usr/local/lib/python3.11/site-packages/celery/backends/redis.py", line 350, in _params_from_url
2023-12-13T22:21:52.326205294Z     connparams['db'] = int(db)
2023-12-13T22:21:52.326211286Z                        ^^^^^^^
2023-12-13T22:21:52.326217267Z ValueError: invalid literal for int() with base 10: ':6379/}'
```

Why is `database "plane:plane@plane-db/plane}"` missing? Isn't the curly brace some typo?

Thanks for clarifying this.

### Browser

Google Chrome

### Version

Self-hosted

**Comment by mguptahub** [comment] 2023-12-14 03:59
We have identified the issue and a PR has been created to fix it.

**Comment by smnbgn** [comment] 2023-12-14 10:02
I have the same problem on Ubuntu 22.04.3 LTS

```
Waiting for database...
Database available!
[2023-12-14 09:59:16,174: CRITICAL/MainProcess] Unrecoverable error: ValueError("invalid literal for int() with base 10: ':6379/}'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 112, in start
    self.on_start()
  File "/usr/local/lib/python3.11/site-packages/celery/apps/worker.py", line 135, in on_start
    self.emit_banner()
  File "/usr/local/lib/python3.11/site-packages/celery/apps/worker.py", line 169, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/apps/worker.py", line 231, in startup_info
    results=self.app.backend.as_uri(),
            ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 1293, in backend
    self._backend = self._get_backend()
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 968, in _get_backend
    return backend(app=self, url=url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/backends/redis.py", line 272, in __init__
    self.connparams = self._params_from_url(url, self.connparams)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/backends/redis.py", line 350, in _params_from_url
    connparams['db'] = int(db)
                       ^^^^^^^
ValueError: invalid literal for int() with base 10: ':6379/}'
```

**Comment by pablohashescobar** [comment] 2023-12-18 18:05
@corbolais, can you check this in the the current version `0.14.1-dev`.

**Comment by tikitavi** [comment] 2023-12-19 13:11
Having the same issue. I've upgraded it to the latest version and the issue is still here

**Comment by tikitavi** [comment] 2023-12-19 13:18
> I had the same problem on Ubuntu 22.04.3 LTS
> 
> I fixed it by changing the following variables in docker-compose.yaml to: - DATABASE_URL=${DATABASE_URL:-postgresql://plane:plane@plane-db/plane} - REDIS_URL=${REDIS_URL:-redis://plane-redis:6379}
> 
> See: #2809

thanks, that helped

**Comment by pablohashescobar** [comment] 2023-12-19 17:37
@tikitavi, just to confirm did you follow the steps [here](https://docs.plane.so/self-hosting/docker-compose).

**Comment by tikitavi** [comment] 2023-12-20 10:42
@pablohashescobar yes, exactly

**Comment by abidkhan484** [comment] 2023-12-20 16:04
Similar found in the latest code of the `preview` branch.

**Comment by smcpeck** [comment] 2024-01-06 03:58
### WORKAROUND

The current `docker-compose.yml` file has some issues with how environment variables are defined based on other variable values.

Assuming you haven't changed any default values/name of your docker deployment, simply make the following adjustment:

~- REDIS_URL=${REDIS_URL:-redis://${REDIS_HOST}:6379/}~
**- REDIS_URL=redis://plane-redis:6379/**

**Comment by apakhbari** [comment] 2024-02-01 10:03
Hi there, thank you for developing this really cool piece of software.
Still have this issue, Changing **REDIS_URL** has not solved problem for me.

**Comment by mguptahub** [comment] 2024-02-21 06:43
@apakhbari / @tikitavi / @smcpeck / @abidkhan484 / @smnbgn 

I have done a successful deployment of Plane Selfhost as per the [documentation](https://docs.plane.so/docker-compose) provided. I have used a Ubuntu 23.10 vm on [DigitalOcean](https://www.digitalocean.com/)

Check the video >> https://www.loom.com/share/f3b049aad3aa4fa299428f5441cfb22c 

Closing this issue for now. Feel free to reopen in case you still face issues.

**Closed by mguptahub** 2024-02-21 06:43 UTC
Labels: 🐛bug, 🏠self-hosted, 🐳docker
