### ISSUE TITLE
[bug]: Tabbing not tabbing properly on Add Module 

### ISSUE THREAD

**Issue by viniciusdel** [makeplane/plane#3261] opened 2023-12-27 14:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When creating a new module in a project, I can tab within all the options like "target date", "backlog", but when it gets to lead, it skips the tabbing to the options that are further down.

The expected behavior is for the tabbing to continue through the remaining options before jumping down.

### Steps to reproduce

When creating a new module in a project, I can tab within all the options like "target date", "backlog", but when it gets to lead, it skips the tabbing to the options that are further down.

### Browser

Other

### Version

Cloud

**Comment by pushya22** [comment] 2024-02-22 07:54
#3332 The issue is fixed in this PR

**Closed by pushya22** 2024-02-22 07:54 UTC
Labels: 🎨UI / UX
