### ISSUE TITLE
[feature]: Enable Special Direct Notifications (Alerts)

### ISSUE THREAD

**Issue by mariliatostesdev** [makeplane/plane#4594] opened 2024-05-24 19:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We need a more noticeable alert system for direct mentions, that differentiates direct mentions from general updates.

When someone is trying to reach me, it would be ideal to be notified separately, maybe with a red token, or something along those lines. 

If there is something like that already, maybe it can be improved, we just haven't felt like it's drawn the user’s attention as it should.

### Why should this be worked on?

Ensures important mentions are not missed. That would prevent the user to have to look through a large number of notifications to get to a mention they sometimes didn't know was there.

Current notifications do not sufficiently draw attention to important mentions, especially when users have a large number of notifications.

**Comment by gchanchal** [comment] 2024-05-29 11:09
duplicate of #4590

**Closed** 2024-09-18 01:03 UTC
Labels: ✨feature
