### ISSUE TITLE
[bug]: workspace creation url with special characters

### ISSUE THREAD

**Issue by razzeee** [makeplane/plane#1263] opened 2023-06-09 11:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I create a workspace and choose a name with some special character like `test/test` the url preview shows the `/` unchanged

### Steps to reproduce

1. Setup a new system
2. click through to workspace creation
3. Write `test/test`

### Browser

Mozilla Firefox

### Version

Local

**Comment by rhea0110** [comment] 2023-06-10 18:56
Hey @razzeee, thank you for your valuable suggestion. We have already planned to implement it soon, and we will keep you updated on the progress.

Thank you!

**Comment by vihar** [comment] 2023-12-14 18:02
@razzeee, thanks for flagging this, and we apologize for the delayed response. @NarayanBavisetti and @aaryan610 will address this issue shortly. 

In the meantime, if you could kindly provide information regarding the expected behavior or suggestions on how to handle this (since '/' will be included in the route), it would greatly assist us in expediting the resolution.

cc: @sriramveeraghanta

**Comment by razzeee** [comment] 2023-12-14 18:17
I think just uri encoding it would be fine - or it would need to be stripped. Depends a bit on your UI/UX, haven't tried this for some time.

**Comment by srinivaspendem** [comment] 2024-05-17 06:40
Hey @razzeee, the issue has been resolved by displaying an alert that informs users they cannot use special characters in the workspace creation.

<img width="956" alt="image" src="https://github.com/makeplane/plane/assets/65014795/85eccb23-7ced-4677-b060-ad255029155b">

**Closed by srinivaspendem** 2024-05-17 06:40 UTC
Labels: 🐛bug, 🛫plane
