### ISSUE TITLE
🚀 Feature: change password in self-hosted solution

### ISSUE THREAD

**Issue by RilusMahmud** [makeplane/plane#1258] opened 2023-06-08 11:50 UTC
Please implement the change password on the self-hosted solution.

**Comment by Pdzly** [comment] 2023-06-08 12:23
dupe of this https://github.com/makeplane/plane/issues/1138

**Comment by Pdzly** [comment] 2023-06-08 12:23
Should be fixed on develop branch btw. it could be bugged but it could work

**Comment by RilusMahmud** [comment] 2023-06-08 12:26
Can you please show me where is the option to change the password? I couldn't find that. Maybe I'm missing something.

**Comment by RilusMahmud** [comment] 2023-06-08 13:00
Alright. But, what I meant by the change password is to change my own password from the profile page.

**Comment by Pdzly** [comment] 2023-06-09 19:46
This is still dupe of #1138

**Comment by vihar** [comment] 2024-07-03 13:15
Sorry for the late follow-up on this. We shipped the option to change the password on our self-hosted instance a few releases back. This can be found under profile > settings > security.​

**Closed by vihar** 2024-07-03 13:15 UTC
Labels: 🛫plane, 🏠self-hosted
