### ISSUE TITLE
[bug]: Show sub-issues is not working properly

### ISSUE THREAD

**Issue by matthieumasse** [makeplane/plane#5738] opened 2024-10-02 13:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i disable "Show sub-issues" some of my issues disappear even if the parent is not present in the view.

I expect to have all issues in my view and IF the issue has its parent in the view, display only under the parent.

### Steps to reproduce

1. Create an issue (IS1) in a project (P1)
2. Create a sub-issue (IS2) in another project (P2)
3. Go to P2 issues view
4. Disable "show sub-issues" then IS2 is not shown anymore

Same if you have the parent issue (IS1) in cycle C1 but sub-issues splited between C1 and C2. Sub-issues on C2 are not shown in C2 issues list if "show sub-issues" is disabled.

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v0.22.0

**Comment by srinivaspendem** [comment] 2024-10-03 09:03
Hey @matthieumasse,

The issue board you're viewing is specific to Project 2. The issues you've created in Project 2, like IS2, are sub-issues.
When you toggle off the "Show sub-issues" option in the display settings, sub-issues such as IS2 (which is linked to IS1 from Project 1) are hidden from view. This happens even when the parent issue is part of a different project or cycle.

Additionally, since IS1 is part of Project 1, it won't appear on the Project 2 board.
The current behavior removes sub-issues from the view entirely when "Show sub-issues" is disabled, which also impacts sub-issues split across cycles. For example, if IS1 is in cycle C1 and IS2 is split between C1 and C2, sub-issues in C2 won't be displayed either.

The expected behavior is for all issues to be shown by default, and if an issue has a parent in the same view, then the sub-issue should appear nested under the parent. However, sub-issues should still be displayed when their parent is in a different project or cycle.

**Comment by srinivaspendem** [comment] 2024-10-04 05:20
We believe the issue has been resolved, so we're closing this issue. However, if you continue to experience any problems, feel free to reopen it.

**Closed by srinivaspendem** 2024-10-04 05:20 UTC
Labels: 🐛bug
