### ISSUE TITLE
[bug]: Project member can't edit their view

### ISSUE THREAD

**Issue by moigagoo** [makeplane/plane#5352] opened 2024-08-12 11:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Update view and Save as button won't appear after view modification. 

### Steps to reproduce

1. Alice is a Viewer in a workspace and a Member in a project.
2. Alice created a view for herself in the project.
3. Alice wants to edit the view. She clicks on it and changes its Display settings.

### Environment

Production

### Browser

None

### Variant

Cloud

### Version

Latest

**Comment by pushya22** [comment] 2024-08-12 12:42
Hi @moigagoo,This issue is occurring because the user has a viewer role at the workspace level, which is currently the intended behaviour of the platform. We are in the process of streamlining all roles across the entire application, which should resolve this issue.

**Comment by moigagoo** [comment] 2024-08-12 12:49
@pushya22 so, the user can create a view but can't edit it, is this correct? Sounds like a bug, to be honest :-)

**Comment by pushya22** [comment] 2024-08-16 08:24
Hi @moigagoo Yes, we are actively working on a fix for this.

**Closed** 2024-08-16 11:05 UTC
Labels: 🐛bug
