### ISSUE TITLE
[bug]: Cannot resize pasted image when there is more than one image in the issue

### ISSUE THREAD

**Issue by bartoszjuszczyk** [makeplane/plane#5051] opened 2024-07-05 06:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

**Current behavior:** 
When I paste an image into an issue comment, I cannot resize it when there are more than just the image I paste into the issue(s).

**Expected behavior:**
After pasting an image into an issue comment, it is possible to change its size

### Steps to reproduce

1. Write comment and paste image to it
2. Write another comment and paste image to it
3. Try to resize pasted image

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v0.21.0

**Comment by jSchenkel** [comment] 2024-07-09 18:17
Hello! I'm currently developing an AI tool that investigates issues, and I used this issue as a test to see if it could help. Below are the findings, which I hope might assist in resolving this issue faster.

**Boosterbot.ai Findings:**
The root cause of the issue is the use of `document.querySelector('.ProseMirror-selectednode')` in the `ImageResizer` component, which only targets the first selected image. This prevents users from resizing other images when more than one image is present in the issue comment section.
1. **Examine the component or module responsible for handling image pasting in issue comments.**
The `IssueCommentCreate` component integrates with the `LiteTextEditor` for text editing and image pasting. The `LiteTextEditor` component's `onChange` handler updates the comment's HTML content, but there is no explicit logic for handling multiple images. The `IssueCommentCard` component renders the comment content, including images, but does not handle image pasting directly.
2. **Investigate the logic or event handlers that enable image resizing.**
The `ImageResizer` component is responsible for enabling users to resize images within the editor. The `onResizeStart`, `onResize`, and `onResizeEnd` handlers are correctly set up to handle resizing. However, the `target` for the `Moveable` component is set to `document.querySelector('.ProseMirror-selectednode')`, which only targets the first selected image. This could be the root cause of the issue.
3. **Review the interaction between multiple images within the same issue comment section.**
The `ImageResizer` component uses `document.querySelector('.ProseMirror-selectednode')` to select the image to be resized. This approach only selects the first element with the class `ProseMirror-selectednode`. If multiple images are present, only the first one will be targeted for resizing. This is likely causing the issue where users cannot resize other images when more than one image is present.

These suggestions are automatically generated based on the context of the issue description and repository code. If you have any feedback or want to try it on your own project, my email is on my profile. Thanks!

**Comment by dByler1** [comment] 2024-07-10 15:21
@bartoszjuszczyk I was not able to reproduce your issue - see screen recording below. If you are still experiencing the issue, can you please make a screen recording to demo the issue? 

https://github.com/makeplane/plane/assets/24251117/28272f26-7863-4d23-9caf-ee7f6d5a05d9

**Comment by aaryan610** [comment] 2024-09-19 13:46
Hey @bartoszjuszczyk, this issue was recently fixed with #5585. It'll be made live with our next release soon.

**Closed by aaryan610** 2024-09-19 13:46 UTC
Labels: 🐛bug, ✍️editor
