### ISSUE TITLE
[bug]: UI completed tasks should not be crossed out

### ISSUE THREAD

**Issue by AlwinEgger** [makeplane/plane#5405] opened 2024-08-21 11:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When issue tasks are completed, the text is stroked through. This makes it harder to read it. Crossed out text seems more like something was planned but later decided not to be done. Completed work should maybe formatted in a different way.

![image](https://github.com/user-attachments/assets/affba1aa-ed7b-4dda-89c5-3668b6621a5f)

### Steps to reproduce

Create tasks in any issue and tick it as done.

### Environment

Production

### Browser

None

### Variant

Cloud

### Version

v1.2.1

**Comment by AlwinEgger** [comment] 2024-08-21 12:26
Might be a duplication of this one: #5394

**Comment by vihar** [comment] 2024-09-18 01:00
Thanks for the feedback, @AlwinEgger. We will pick this up shortly. Closing this issue as it is a duplicate of #5394.

**Closed by vihar** 2024-09-18 01:00 UTC
Labels: 🐛bug, pages
