### ISSUE TITLE
[bug]: Unable to create workspace on onboarding.

### ISSUE THREAD

**Issue by prathamjagga** [makeplane/plane#2882] opened 2023-11-26 19:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://github.com/makeplane/plane/assets/30550632/035ef04e-4431-4361-bf51-523754a66f44)
problem is in WorkSpaceViewSet create method.

### Steps to reproduce

Run docker compose up.
Open localhost/sign-up
Add workspace
Shows error.

### Browser

Google Chrome

### Version

Local - Self hosted - master branch

**Comment by dnamesh** [comment] 2023-12-09 10:15
Any update on this?

**Comment by pablohashescobar** [comment] 2023-12-11 10:58
we are unable to reproduce this on our end. Can you check on the current `develop` branch.

**Comment by pablohashescobar** [comment] 2023-12-15 05:52
We are closing this issue as we were unable to replicate the problem. Please ensure you are using the latest version. If you continue to experience this issue after updating, kindly let us know and we will investigate further.

**Closed by pablohashescobar** 2023-12-15 05:52 UTC
Labels: 🏠self-hosted
