### ISSUE TITLE
[bug]: right sidebar content overflow

### ISSUE THREAD

**Issue by ChandanJal** [makeplane/plane#1362] opened 2023-06-22 12:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you have really large **title** and **description** content. Sidebar getting overflow
![RIGHT SIDE BAR CONTENT OVER FLOW](https://github.com/makeplane/plane/assets/97095857/fc96530e-1790-49ec-b39d-e0cc7f4f3374)

### Steps to reproduce

1. Create new `Circle` with large `Title` and `Description`
2. Go to the detail page of the `Circle`

### Browser

Google Chrome

### Version

Cloud

**Comment by kblueberry** [comment] 2023-06-24 13:49
@ChandanJal the issue is not reproducible on my side, you can re-check on you side, and if the same - we can close it

**Closed** 2023-12-14 18:11 UTC
Labels: 🐛bug, 🛫plane
