### ISSUE TITLE
[feature]: Undo functionality while using editor

### ISSUE THREAD

**Issue by JWalshe86** [makeplane/plane#4607] opened 2024-05-27 12:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I can't find an option to undo work while using the editor

I would like to be able to click on an undo button in the task bar. 

### Why should this be worked on?

This would enable me to quickly roll back on work if required, instead of having to manually delete it. It would be more efficient.

**Comment by vihar** [comment] 2024-06-29 10:38
@JWalshe86, we support undo and redo functionality on the page and in the issue rich text editor. We follow standard shortcuts: for undo, use `Command/Ctrl + Z`, and for redo, use `Command/Ctrl + Shift + Z`. We will consider adding a button on the toolbar to improve the experience. Thanks for sharing your feedback.

**Comment by copy1dollar** [comment] 2024-08-22 01:56
Rich text editors cannot be used in issues or issue comments.
Is there a way to enable them?
Currently, since rich text editors are not available, the Ctrl + Z shortcut does not work.

**Comment by shafay07** [comment] 2024-08-31 09:33
I can confirm that on version 0.22.0, the "Ctrl + Z" undo functionality is not working in the issue description editor, although it works fine in issue titles and other fields. This bug forced me to rewrite a 500-word description, which was highly inconvenient. Please prioritize and expedite the resolution of this issue.

**Comment by aaryan610** [comment] 2024-09-19 13:49
Hey @JWalshe86, this issue was fixed with #5133.

**Closed by aaryan610** 2024-09-19 13:49 UTC
Labels: ✨feature, ✍️editor
